# AIX NFS Monitor Extension Configuration

# Metric prefix for AppDynamics
metricPrefix: "Custom Metrics|AIX NFS Monitor|"

# URL to fetch centralized configuration (supports {inventory_hostname} placeholder)
configUrl: "https://raw.githubusercontent.com/your-org/nfs-monitoring-configs/main/{inventory_hostname}.json"

# Number of threads for processing
numberOfThreads: 2

# Task schedule in seconds
taskSchedule:
  numberOfThreads: 2
  taskDelaySeconds: 60

# Metric write helper configuration
metricWriteHelper:
  metricPrefix: "Custom Metrics|AIX NFS Monitor|"
  
# Servers configuration (required by base monitor)
servers:
  - host: "localhost"
    port: 8080
    useSSL: false

# AIX-specific commands configuration
aixCommands:
  df: "df -k"

# Metrics configuration
metrics:
  - Total Space (KB):
      alias: "Total Space (KB)"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
  - Free Space (KB):
      alias: "Free Space (KB)"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
  - Used Space (KB):
      alias: "Used Space (KB)"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
  - Usage Percentage:
      alias: "Usage Percentage"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
  - Available:
      alias: "Available"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"