# AIX Service Monitor Extension Configuration

# Metric prefix for AppDynamics
metricPrefix: "Custom Metrics|AIX Service Monitor|"

# URL to fetch centralized configuration (supports {inventory_hostname} placeholder)
configUrl: "https://raw.githubusercontent.com/your-org/service-monitoring-configs/main/{inventory_hostname}.json"

# Number of threads for processing
numberOfThreads: 2

# Task schedule in seconds
taskSchedule:
  numberOfThreads: 2
  taskDelaySeconds: 60

# Metric write helper configuration
metricWriteHelper:
  metricPrefix: "Custom Metrics|AIX Service Monitor|"
  
# Servers configuration (required by base monitor)
servers:
  - host: "localhost"
    port: 8080
    useSSL: false

# AIX-specific commands configuration
aixCommands:
  lssrc: "lssrc -s"
  ps: "ps -ef"
  psUptime: "ps -o etime= -p"

# Metrics configuration
metrics:
  - Status:
      alias: "Service Status"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
  - Uptime (seconds):
      alias: "Service Uptime (seconds)"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"